mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from polls.views import loginView, logoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls')),
    path('login/', loginView, name="login"),
    path('logout/', logoutView, name="logout")
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("poll/new/", views.questionCreation, name="create"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

polls/models.py
from django.db import models
from django.shortcuts import reverse
from django.utils import timezone
from django.contrib.auth import get_user_model
import datetime

User = get_user_model()

# Create your models here.


class Question(models.Model):
    question_text = models.CharField(max_length=200, null=False)
    pub_date = models.DateTimeField(default=timezone.now)

    def was_published_recently(self):
        now = timezone.now()
        return now >= self.pub_date >= now-datetime.timedelta(days=1)

    def __str__(self):
        return self.question_text

    def get_absolute_url(self):
        return reverse("polls:index")


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.ManyToManyField(User)

    def __str__(self):
        return self.choice_text

polls/forms.py
from django import forms
from django.forms import widgets
from .models import Question, Choice, User


class QuestionCreationForm(forms.Form):
    question_text = forms.CharField(max_length=100, widget=widgets.TextInput(
        attrs={'placeholder': 'Enter your question'}))
    choice1 = forms.CharField(max_length=255)
    choice2 = forms.CharField(max_length=255)

    def save(self):
        validated_data = self.cleaned_data
        self.create(validated_data)

    def create(self, validated_data):
        question_text = validated_data.get('question_text', "")
        choice1 = validated_data.get('choice1', "")
        choice2 = validated_data.get('choice2', "")

        question = Question.objects.create(question_text=question_text)
        Choice.objects.create(question=question, choice_text=choice1)
        Choice.objects.create(question=question, choice_text=choice2)


class LoginForm(forms.Form):
    username = forms.CharField(max_length=100, widget=widgets.TextInput(
        attrs={'placeholder': 'Enter your username'}))
    password = forms.CharField(max_length=100, widget=widgets.PasswordInput(
        attrs={'placeholder': 'Enter your username'}))

polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views import generic
from django.contrib import messages
from django.contrib.auth.hashers import check_password
from django.contrib.auth import login, logout

from .models import Question, Choice, User
from .forms import LoginForm, QuestionCreationForm
from .decorators import no_user_required


class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        return Question.objects.order_by("-pub_date")


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except(KeyError, Choice.DoesNotExist):
        messages.warning(request, "You haven't selected any choice")
        return render(request, 'polls/detail.html', {
            'question': question,
        })
    else:
        selected_choice.votes.add(request.user)
        selected_choice.save()
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))


def questionCreation(request):
    if request.method == "POST":
        form = QuestionCreationForm(request.POST)
        if form.is_valid() and request.user.is_staff:
            form.save()
            return redirect("polls:index")
        else:
            return redirect("polls:index")

    else:
        form = QuestionCreationForm()

    return render(request, "polls/question_form.html", {"form": form})


@no_user_required
def loginView(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username", "")
            password = form.cleaned_data.get("password", "")
            user = get_object_or_404(User, username=username)
            if check_password(password, user.password):
                login(request, user)
                messages.success(
                    request, f"successfully login {user.username}")
                return redirect("polls:index")
            messages.warning(request, "please check your credentials")
            return render(request, 'registration/login.html', {"form": form})
        messages.warning(request, "please check your credentials")
        return render(request, 'registration/login.html', {"form": form})
    form = LoginForm()
    return render(request, 'registration/login.html', {"form": form})


def logoutView(request):
    logout(request)
    return redirect("login")

polls/templates/polls/detail.html
<h1> {{ question.question_text }} </h1>

{% if error_message %}
    <p> <strong> {{ error_message }} </strong> </p>
{% endif %}

<form action={% url 'polls:vote' question.id %} method='post'>
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{choice.id}}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
    <input type="submit" value="Vote">
</form>

polls/templates/polls/question_form.html
<form action="" method="POST">
  {% csrf_token %}
    {{ form }}
  <button type="submit">Submit</button>
</form>

polls/templates/polls/results.html
<h1> {{ question.question_text }} </h1>

<ul>
    {% for choice in question.choice_set.all %}
        <li> {{choice.choice_text }} -- {{choice.votes }} vote{{choice.votes | pluralize }} </li>
    {% endfor %}
</ul>

<a href={% url 'polls:detail' question.id %}> Vote again? </a>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <title>Django Polling App {% block title %} {% endblock title %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href={% url 'polls:index' %}>Navbar</a>
      
        <div class="collapse navbar-collapse offset-3" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href={% url 'polls:index' %}>Home</a>
            </li>
            {% if user.is_staff %}
              <li class="nav-item">
                <a class="nav-link" href={% url 'polls:create' %}>New Poll</a>
              </li>
            {% endif %}
            {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href={% url "logout" %}> LogOut </a>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link" href={% url "login" %}> LogIn </a>
              </li>
            {% endif %}
          </ul>
        </div>

      </div>
    </nav>
    <div class="container">
      <div class="row">
        <div class="col-md-6 pt-2 m-auto">
          {% if messages %}
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }} row" role="alert">
                  <div class="col-11">{{ message }}</div>
                  <button type="button" class="btn-close col-1" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
            {% endif %}
          {% block content %} {% endblock content %}
        </div>
      </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
  </body>
</html>

templates/polls/detail.html
{% extends "base.html" %}
{% block content %}
<h1> {{ question.question_text }} </h1>

<form action={% url 'polls:vote' question.id %} method='post'>
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{choice.id}}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
    <input type="submit" value="Vote">
</form>
{% endblock content %}

templates/polls/index.html
{% extends "base.html" %}
{% block content %}
{% if latest_question_list %}
  <ul>
    {% for question in latest_question_list %}
    	<li><a href={% url 'polls:detail' question.id %}> {{question.question_text }} </a></li>
    {% endfor %}
  </ul>

{% else %}
	<p> No polls are available. </p>
{% endif %}

{% endblock content %}
    

templates/polls/question_form.html
{% extends "base.html" %} {% load crispy_forms_tags %}
 {% block content %}
 <div class="content-section row">
  <form action="" method="POST" class="col-10">
    {% csrf_token %}
    <fieldset class="form-group">
      <legend class="border-bottom md-4">Create Poll</legend>
      {{form | crispy }}
    </fieldset>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>
{% endblock content %}

templates/polls/results.html
{% extends "base.html" %}
{% block content %}
<h1> {{ question.question_text }} </h1>

<ul>
    {% for choice in question.choice_set.all %}
        <li> {{choice.choice_text }} -- {{choice.votes.count }} vote{{choice.votes.count | pluralize }} </li>
    {% endfor %}
</ul>

<a href={% url 'polls:detail' question.id %}> Vote again? </a>
{% endblock content %}